export const musicStore = [
  {
    id: 1,
    store: "Spotify",
    link: "https://open.spotify.com/album/43wtwG3mCsFNg54a66H2Sm",
    logo: "spotify",
    action: "PLAY",
  },
  {
    id: 2,
    store: "Apple Music",
    link: "https://geo.music.apple.com/us/album/_/1759864861?mt=1&app=music",
    logo: "apple",
    action: "BUY",
  },
  {
    id: 3,
    store: "iTunes",
    link: "https://geo.music.apple.com/us/album/_/1759864861?mt=1&app=itunes",
    logo: "itunes",
    action: "BUY",
  },
  {
    id: 4,
    store: "Deezer",
    link: "https://www.deezer.com/album/621587931",
    logo: "deezer",
    action: "PLAY",
  },
  {
    id: 5,
    store: "Audiomack",
    link: "https://audiomack.com/deveryboy/album/believe-1?share-user-id=26238173",
    logo: "audiomack",
    action: "PLAY",
  },
  {
    id: 6,
    store: "Youtube Music",
    link: "https://music.youtube.com/playlist?list=OLAK5uy_n4DXMj5mpzu0zdKrbLon0REEKP_pViuu4",
    logo: "youtube",
    action: "PLAY",
  },
  {
    id: 7,
    store: "Boomplay",
    link: "https://www.boomplay.com/albums/94999187",
    logo: "boomplay",
    action: "PLAY",
  },
  {
    id: 8,
    store: "Tidal",
    link: "https://listen.tidal.com/album/377945156",
    logo: "tidal",
    action: "PLAY",
  },
  {
    id: 9,
    store: "Youtube",
    link: "https://www.youtube.com/playlist?list=OLAK5uy_n4DXMj5mpzu0zdKrbLon0REEKP_pViuu4",
    logo: "youtubelogo",
    action: "WATCH",
  },  {
    id: 10,
    store: "SoundCloud",
    link: "https://soundcloud.com/deveryboy/sets/believe-411925260",
    logo: "soundcloud",
    action: "PLAY",
  },  {
    id: 11,
    store: "Napster",
    link: "https://us.napster.com/66a66a275b09f1048ffd4389",
    logo: "napster",
    action: "BUY",
  },  {
    id: 12,
    store: "Tiktok",
    link: "https://vm.tiktok.com/ZMrV1jWk9/",
    logo: "tiktok",
    action: "USE SOUND",
  },  {
    id: 13,
    store: "Dml Blog",
    link: "https://www.demusiclinkup.com.ng/2024/07/album-deveryboy-believe.html",
    logo: "dml",
    action: "DOWNLOAD",
  },  {
    id: 14,
    store: "Afrotonez Blog",
    link: "https://afrotonez.com.ng/album-deveryboy-believe/",
    logo: "afro",
    action: "DOWNLOAD",
  },

];
